embedding_size: 64
feat_embed_dim: 64

n_layers: [2]
dropout: [0.3]
reg_weight: [0.01]
cl_weight: 2.0

use_neg_sampling: False

missing_modal : 0
missing_imputation : [0]

new_items : 0

hyper_parameters: ["n_layers", "reg_weight", "dropout",  "missing_imputation"]

